# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.fcaorderer.com:
  peer0.jeep.fca.com:
  peer1.jeep.fca.com:
  peer0.jeepdealer.fca.com:
  peer1.jeepdealer.fca.com:
  peer0.jeeplogistics.fca.com:
  peer1.jeeplogistics.fca.com:
  peer0.jeeptrucking.fca.com:
  peer1.jeeptrucking.fca.com: 
  peer0.cbp.gov:
  peer1.cbp.gov:  

networks:
  byfn:

services:

  orderer.fcaorderer.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.fcaorderer.com
    container_name: orderer.fcaorderer.com
    networks:
      - byfn

  peer0.jeep.fca.com:
    container_name: peer0.jeep.fca.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.jeep.fca.com
    networks:
      - byfn

  peer1.jeep.fca.com:
    container_name: peer1.jeep.fca.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.jeep.fca.com
    networks:
      - byfn

  peer0.jeepdealer.fca.com:
    container_name: peer0.jeepdealer.fca.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.jeepdealer.fca.com
    networks:
      - byfn

  peer1.jeepdealer.fca.com:
    container_name: peer1.jeepdealer.fca.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.jeepdealer.fca.com
    networks:
      - byfn

  peer0.jeeplogistics.fca.com:
    container_name: peer0.jeeplogistics.fca.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.jeeplogistics.fca.com
    networks:
      - byfn

  peer1.jeeplogistics.fca.com:
    container_name: peer1.jeeplogistics.fca.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.jeeplogistics.fca.com
    networks:
      - byfn

  peer0.jeeptrucking.fca.com:
    container_name: peer0.jeeptrucking.fca.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.jeeptrucking.fca.com
    networks:
      - byfn

  peer1.jeeptrucking.fca.com:
    container_name: peer1.jeeptrucking.fca.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.jeeptrucking.fca.com
    networks:
      - byfn

  peer0.cbp.gov:
    container_name: peer0.cbp.gov
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.cbp.gov
    networks:
      - byfn

  peer1.cbp.gov:
    container_name: peer1.cbp.gov
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.cbp.gov
    networks:
      - byfn


  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.jeep.fca.com:7051
      - CORE_PEER_LOCALMSPID=JeepMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/jeep.fca.com/peers/peer0.jeep.fca.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/jeep.fca.com/peers/peer0.jeep.fca.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/jeep.fca.com/peers/peer0.jeep.fca.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/jeep.fca.com/users/Admin@jeep.fca.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.fcaorderer.com
      - peer0.jeep.fca.com
      - peer1.jeep.fca.com
      - peer0.jeepdealer.fca.com
      - peer1.jeepdealer.fca.com
      - peer0.jeeplogistics.fca.com
      - peer1.jeeplogistics.fca.com
      - peer0.jeeptrucking.fca.com
      - peer1.jeeptrucking.fca.com
      - peer0.cbp.gov
      - peer1.cbp.gov
    networks:
      - byfn
