/* eslint-disable prettier/prettier */
export default {
  vehicleFields: [
    { label: 'carNumber', field: 'input', type: 'text', className: 'form-input', editable: false },
    { label: 'ProductID', field: 'input', type: 'text', className: 'form-input', editable: false },
    { label: 'CarMaker', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'CarModel', field: 'input', type: 'select', className: 'form-input', editable: true },
    { label: 'CarColor', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'CarModelYear', field: 'input', type: 'select', className: 'form-input', editable: true },
    { label: 'CarPrice', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'CustomerName', field: 'input', type: 'text', className: 'form-input', editable: false }
  ],
  orderFields: [
    { label: 'carNumber', field: 'input', type: 'text', className: 'form-input', editable: false },
    { label: 'OrderID', field: 'input', type: 'text', className: 'form-input', editable: false },
    { label: 'OrderDate', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'SupplierName', field: 'input', type: 'text', className: 'form-input', editable: false },
    { label: 'CustomerID', field: 'input', type: 'text', className: 'form-input', editable: false },
    { label: 'ShipDate', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'ShipMode', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'Shipping', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'Quantity', field: 'input', type: 'text', className: 'form-input', editable: true }
  ],
  supplierFields: [
    { label: 'carNumber', field: 'input', type: 'text', className: 'form-input', editable: false },
    { label: 'SupplierName', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'SupplierAddress', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'SupplierContactDetails', field: 'input', type: 'text', className: 'form-input', editable: true }
  ],
  customerFields: [
    { label: 'carNumber', field: 'input', type: 'text', className: 'form-input', editable: false },
    { label: 'CustomerID', field: 'input', type: 'text', className: 'form-input', editable: false },
    { label: 'CustomerName', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'Gender', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'JobTitle', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'PhoneNumber', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'EmailAddress', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'City', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'Country', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'CountryCode', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'State', field: 'input', type: 'text', className: 'form-input', editable: true }
  ],
  allFields: [
    { label: 'carNumber', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'SupplierID', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'SupplierAddress', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'SupplierName', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'SupplierContactDetails', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'ProductID', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'CarMaker', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'CarModel', field: 'input', type: 'select', className: 'form-input', editable: true },
    { label: 'CarColor', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'CarModelYear', field: 'input', type: 'select', className: 'form-input', editable: true },
    { label: 'CarPrice', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'CustomerID', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'CustomerName', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'Gender', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'JobTitle', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'PhoneNumber', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'EmailAddress', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'City', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'Country', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'CountryCode', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'State', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'CustomerAddress', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'OrderDate', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'OrderID', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'ShipDate', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'ShipMode', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'Shipping', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'PostalCode', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'Sales', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'Quantity', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'Discount', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'CreditCardType', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'CreditCard', field: 'input', type: 'text', className: 'form-input', editable: true },
    { label: 'CustomerFeedback', field: 'input', type: 'text', className: 'form-input', editable: true }
  ]
};
